final List<String> skillsList = [
  // Creative & Visual
  'Graphic Design',
  'UI/UX Design',
  'Video Editing',
  'Audio Editing',
  'Animation',
  'Photography',
  'Illustration',
  'Motion Graphics',
  '3D Modeling',
  'Branding',
  'Typography',
  'Visual Storytelling',
  'Art Direction',
  'Game Design',
  'AR/VR Design',
  'User Research',
  'Interaction Design (IxD)',
  'Visual Effects (VFX)',
  'Sound Design',
  'Product Photography',
  'UI Animation',
  'Motion Capture',
  'Video Game Art',
  '2D/3D Animation',

  // Marketing & Advertising
  'Digital Marketing',
  'Content Writing',
  'SEO',
  'Social Media Marketing',
  'Email Marketing',
  'Copywriting',
  'Paid Advertising',
  'Market Research',
  'Affiliate Marketing',
  'Influencer Marketing',
  'Conversion Rate Optimization',
  'Marketing Analytics',
  'Public Relations',
  'Customer Relationship Management',
  'Growth Hacking',
  'App Store Optimization (ASO)',
  'Content Strategy',
  'Video Marketing',
  'Community Management',
  'Event Marketing',
  'Retargeting Ads',
  'Brand Strategy',
  'Consumer Behavior Analysis',
  'Loyalty Programs',
  'Data-Driven Marketing',
  'Chatbot Marketing',
  'Podcast Marketing',
  'Influencer Campaign Management',

  // Software & Development
  'Flutter',
  'React',
  'Node.js',
  'Python',
  'Django',
  'Machine Learning',
  'Data Science',
  'Web Development',
  'Frontend Development',
  'Backend Development',
  'Mobile App Development',
  'JavaScript',
  'TypeScript',
  'Swift',
  'Kotlin',
  'Rust',
  'Go',
  'C++',
  'PHP',
  'Ruby on Rails',
  'ASP.NET',
  'GraphQL',
  'API Development',
  'Software Architecture',
  'Embedded Systems',
  'Game Development',
  'Flutter/Dart',
  'Kotlin Multiplatform',
  'Firebase',
  'GraphQL APIs',
  'TensorFlow',
  'Android Development',
  'iOS Development',
  'Git/GitHub/GitLab',
  'Continuous Integration (CI/CD)',
  'Mobile Game Development',
  'Augmented Reality (AR)',
  'Virtual Reality (VR)',
  'Internet of Things (IoT)',
  'Cloud-Native Development',
  'Serverless Architecture',
  'JAMstack Development',
  'Flutter Web',
  'TypeScript/React Native',
  'MongoDB',
  'Elasticsearch',
  'Redis',

  // IT & Cloud
  'Cloud Computing',
  'Cybersecurity',
  'DevOps',
  'IT Support',
  'Network Administration',
  'Database Management',
  'System Administration',
  'AI & Deep Learning',
  'Blockchain',
  'Ethical Hacking',
  'Linux Administration',
  'Serverless Computing',
  'Kubernetes',
  'IT Security Compliance',
  'IT Helpdesk',
  'Cloud Security',
  'Cloud Storage Solutions (AWS S3, Google Cloud Storage)',
  'Google Cloud Platform (GCP)',
  'Microsoft Azure',
  'SAP Cloud Platform',
  'Data Privacy & GDPR Compliance',
  'Cloud-native Security',
  'Cloud Cost Management',
  'Big Data Analytics',
  'Data Warehousing',
  'Data Lakes',
  'Site Reliability Engineering (SRE)',
  'IT Infrastructure Automation',
  'Private Cloud Management',
];
