final List<String> technologiesList = [
  // Frontend Technologies
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'React',
  'Vue.js',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Sass/SCSS',
  'Tailwind CSS',
  'Bootstrap',
  'Material-UI',
  'Ant Design',
  'Chakra UI',

  // Mobile Development
  'Flutter',
  'React Native',
  'iOS',
  'Android',
  'Swift',
  'Kotlin',
  'Dart',
  'Xamarin',
  'Ionic',
  'Cordova',
  'Unity',

  // Backend Technologies
  'Node.js',
  'Express.js',
  'Django',
  'Flask',
  'FastAPI',
  'Ruby on Rails',
  'ASP.NET',
  'Spring Boot',
  'Laravel',
  'CodeIgniter',
  'Symfony',
  'NestJS',
  'Koa.js',
  'Hapi.js',

  // Programming Languages
  'Python',
  'JavaScript',
  'TypeScript',
  'Java',
  'C#',
  'C++',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Swift',
  'Kotlin',
  'Dart',
  'Scala',
  'R',
  'MATLAB',

  // Databases
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'SQLite',
  'Oracle',
  'SQL Server',
  'DynamoDB',
  'Cassandra',
  'Elasticsearch',
  'Neo4j',
  'Firebase Firestore',
  'CouchDB',

  // Cloud & DevOps
  'AWS',
  'Google Cloud Platform',
  'Microsoft Azure',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'GitHub Actions',
  'GitLab CI',
  'Terraform',
  'Ansible',
  'Nginx',
  'Apache',
  'Linux',
  'Ubuntu',
  'CentOS',

  // AI & Machine Learning
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'OpenCV',
  'Keras',
  'Pandas',
  'NumPy',
  'Jupyter',
  'Machine Learning',
  'Deep Learning',
  'Natural Language Processing',
  'Computer Vision',
  'Neural Networks',

  // Digital Marketing & Analytics
  'Google Analytics',
  'Facebook Ads',
  'Google Ads',
  'Instagram Ads',
  'LinkedIn Ads',
  'Twitter Ads',
  'SEO',
  'SEM',
  'Google Tag Manager',
  'Hotjar',
  'Mixpanel',
  'Amplitude',
  'Mailchimp',
  'HubSpot',
  'Salesforce',

  // Design & Creative
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe XD',
  'Figma',
  'Sketch',
  'InVision',
  'Canva',
  'After Effects',
  'Premiere Pro',
  'Blender',
  'Cinema 4D',
  'Maya',
  '3ds Max',
  'AutoCAD',
  'SketchUp',

  // E-commerce & CMS
  'WordPress',
  'Shopify',
  'WooCommerce',
  'Magento',
  'Drupal',
  'Joomla',
  'Webflow',
  'Squarespace',
  'BigCommerce',
  'PrestaShop',
  'OpenCart',

  // Blockchain & Cryptocurrency
  'Ethereum',
  'Bitcoin',
  'Solidity',
  'Web3.js',
  'Hyperledger',
  'Smart Contracts',
  'DeFi',
  'NFT',
  'Metamask',
  'Truffle',

  // Testing & Quality Assurance
  'Jest',
  'Cypress',
  'Selenium',
  'Postman',
  'JMeter',
  'Pytest',
  'Unit Testing',
  'Integration Testing',
  'API Testing',
  'Performance Testing',
  'Automation Testing',

  // Project Management & Collaboration
  'Jira',
  'Trello',
  'Asana',
  'Slack',
  'Microsoft Teams',
  'Zoom',
  'Notion',
  'Confluence',
  'Monday.com',
  'ClickUp',

  // Version Control & Development Tools
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'VS Code',
  'IntelliJ IDEA',
  'PyCharm',
  'Eclipse',
  'Xcode',
  'Android Studio',

  // Game Development
  'Unity',
  'Unreal Engine',
  'Godot',
  'GameMaker Studio',
  'Construct',
  'RPG Maker',
  'Blender Game Engine',

  // IoT & Hardware
  'Arduino',
  'Raspberry Pi',
  'ESP32',
  'MQTT',
  'LoRaWAN',
  'Zigbee',
  'Internet of Things',
  'Embedded Systems',
  'Microcontrollers',

  // Business Intelligence & Data
  'Tableau',
  'Power BI',
  'Looker',
  'QlikView',
  'Apache Spark',
  'Hadoop',
  'Kafka',
  'ETL',
  'Data Warehousing',
  'Big Data',
  'Data Mining',
];
